#!/usr/bin/env bash

contentCollection="content/AUTOGEN_contentCollection.tex"
appendixCollection="appendix/AUTOGEN_appendixCollection.tex"

autogenWarning="% This file is autogenerated. Do not edit it manually. Changes will be lost.\n"

# Content Collection
echo -e "$autogenWarning" > "$contentCollection"

for CONTENT in $(find content -name "*.tex" | grep -v "abstract.tex" | grep -v "AUTOGEN" | sort)
do
    echo "\\include{$CONTENT}"
    mkdir -p auxiliary/$(dirname $CONTENT)
done >>"$contentCollection"

# Appendix Collection
echo -e "$autogenWarning" > "$appendixCollection"

for APPEND in $(find appendix -name "*.tex" | grep -v "AUTOGEN" | sort)
do
    echo "\\include{$APPEND}"
    mkdir -p auxiliary/$(dirname $APPEND)
done >>"$appendixCollection"

mkdir -p auxiliary/frame
