#!/bin/bash

autogenWarning="% This file is autogenerated. Do not edit it manually. Changes will be lost.\n"

# Content Collection
echo -e "$autogenWarning" > content/AUTOGEN_contentCollection.tex

for CONTENT in $(find content -name "*.tex" | grep -v "abstract.tex" | grep -v "AUTOGEN")
do
    echo "\\include{$CONTENT}"
    mkdir -p auxiliary/$(dirname $CONTENT)
done >>content/AUTOGEN_contentCollection.tex

# Appendix Collection
echo -e "$autogenWarning" > appendix/AUTOGEN_appendixCollection.tex

for APPEND in $(find appendix -name "*.tex" | grep -v "AUTOGEN")
do
    echo "\\include{$APPEND}"
    mkdir -p auxiliary/$(dirname $APPEND)
done >>appendix/AUTOGEN_appendixCollection.tex
