noChangesFile="auxiliary/AUTOGEN_noChanges.tex"

autogenWarning="% This file is autogenerated. Do not edit it manually. Changes will be lost.\n"

# Content Collection
echo -e "$autogenWarning" > "$noChangesFile"

if [ -z "$includeonly" ]; then
    echo "\newpage Did not register changes in \textit{content} and \textit{appendix} files so the fast compilation results in an empty document." > "$noChangesFile"
    
    echo "\\input{"$noChangesFile"}">>"content/AUTOGEN_contentCollection.tex"
fi
