#!/bin/bash

autogenWarning="% This file is autogenerated. Do not edit it manually. Changes will be lost.\n"

inotifywait -m -e CLOSE_WRITE . |
while read -r file; do
  if [[ $file != *"indent.log" ]]; then
    continue
  fi

  fileName=$(cat indent.log | grep "Filename:" | awk '{print $NF}' | sed 's|/workspaces/VSCTeX/||g' | sed 's/__latexindent_temp_//' | sed 's/.tex//')

  if ! grep -wq "$fileName" content/AUTOGEN_contentCollection.tex && ! grep -wq "$fileName" appendix/AUTOGEN_appendixCollection.tex || grep -wq "$fileName" frame/AUTOGEN_includeonly.tex || grep -wq "$fileName" frame/AUTOGEN_includeonly.tex; then
    continue
  fi

  includeonlyContent=$(cat frame/AUTOGEN_includeonly.tex | grep -Po '(?<=\\includeonly{).*(?=})')
  
  echo -e "$autogenWarning" > frame/AUTOGEN_includeonly.tex
  
  if [ -z "$includeonlyContent" ]; then
    includeonlyContent="$fileName"
  else
    includeonlyContent="$includeonlyContent,$fileName"
  fi
  
  echo "\\includeonly{$includeonlyContent}" >> frame/AUTOGEN_includeonly.tex
done
