name: Recurring Build Check

on:
  schedule:
    # Runs at 06:00 UTC every Sunday
    - cron: "0 6 * * 0"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-check:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Docker
        uses: docker/setup-docker-action@v4

      - name: Build and test DevContainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: vsctex
          noCache: true
          runCmd: |
            grep -c "watchFileChanges" .devcontainer/devContLog.txt | grep -q "^1$" || exit 1

      - name: Upload resulting document
        uses: actions/upload-artifact@v4
        with:
          name: document_template
          path: ./main.pdf
          if-no-files-found: 'error'
          retention-days: 14
          compression-level: 9
