name: Recurring Build Check

on:
  schedule:
    # Runs at 10:00 UTC every Sunday
    - cron: "0 10 * * 0"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-check:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest-large]

    steps:
      - uses: actions/checkout@v4

      - name: Install and verify Docker
        uses: docker/setup-docker-action@v4
        timeout-minutes: 12
      - run: |
          set -x

          docker version
  
          docker info

      - name: Build and Test DevContainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            echo "Running tests in devcontainer"
