name: Recurring Build Check

on:
  schedule:
    # Runs at 10:00 UTC every Sunday
    - cron: "0 10 * * 0"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-check:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Docker
        uses: docker/setup-docker-action@v4

      - name: Build and test DevContainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          imageName: vsctex
          runCmd: |
            if [[ "$(service --status-all 2>&1)" != *"[ ? ]  devContainerService"* ]]; then exit 1; fi
